<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><AssemblyName>Assembly-CSharp</AssemblyName><AssemblyVersion>0.0.0.0</AssemblyVersion><RootNamespace /></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Il2Cppmscorlib/Il2Cppmscorlib.csproj" Private="false" />
    <ProjectReference Include="../UnityEngine.CoreModule/UnityEngine.CoreModule.csproj" Private="false" />
  </ItemGroup>
</Project>
