<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>UnityEngine.TextRenderingModule</AssemblyName>
    <AssemblyVersion>0.0.0.0</AssemblyVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Il2Cppmscorlib\Il2Cppmscorlib.csproj" />
    <ProjectReference Include="..\UnityEngine.CoreModule\UnityEngine.CoreModule.csproj" />
  </ItemGroup>
</Project>
