#!/usr/bin/env python3
"""Generates the winmm.dll proxy export table from a list of export names.

usage: gen_proxy_exports.py exports.txt src/loader
The list comes from the MinGW import library:
  x86_64-w64-mingw32-nm libwinmm.a | awk '/ T /{print $3}' | grep -v '^[._]' | sort -u
"""
import sys, os

names = [l.strip() for l in open(sys.argv[1]) if l.strip()]
out = sys.argv[2]
with open(os.path.join(out, "winmm_exports.h"), "w") as f:
    f.write("/* Generated by tools/gen_proxy_exports.py. */\n")
    for n in names:
        f.write("X(%s)\n" % n)
with open(os.path.join(out, "winmm.def"), "w") as f:
    f.write("; Generated by tools/gen_proxy_exports.py.\nLIBRARY winmm.dll\nEXPORTS\n")
    for n in names:
        f.write("    %s = fwd_%s\n" % (n, n))
print("%d exports" % len(names))
