<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>KingdomEightCrowns</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>12.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>../../refs2/Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>../../refs2/UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppInterop.Runtime">
      <HintPath>../../orig/Il2CppInterop.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>../../orig/0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="BepInEx.Core">
      <HintPath>../../orig/BepInEx.Core.dll</HintPath>
    </Reference>
    <Reference Include="BepInEx.Unity.IL2CPP">
      <HintPath>../../orig/BepInEx.Unity.IL2CPP.dll</HintPath>
    </Reference>
    <Reference Include="Il2Cppmscorlib">
      <HintPath>../../refs2/Il2Cppmscorlib.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>